class McFunction():
    """
    A class representing a Minecraft function file.
    """

    def __init__(self, file_location: str):
        """
        Initialize the McFunction with a name and a list of commands.

        :param name: The name of the function file.
        :param commands: A list of commands to be included in the function file.
        """
        self.file_location = file_location
        self.file = open(file_location, "w", encoding="utf-8")
        self._write_header()

    def __str__(self) -> str:
        """
        Return a string representation of the function file.

        :return: A string containing the function file's name and commands.
        """
        return f"{self.name}\n"

    def write_header(self):
        """
        Write the header to the function file.
        """
        header_lines = [
            "# Minecraft function file",
            "# This file was created by Reddition",
            "# Do not edit this file manually",
            "",
        ]
        for line in header_lines:
            self.write_line(line)
    
    def write_line(self, text: str):
        """
        Write a line to the function file.

        :param text: The line of text to write.
        """
        self.file.write(text + "\n")

    def write(self, text: str):
        """
        Write text to the function file.

        :param text: The text to write.
        """
        self.file.write(text)

    def clear_file(self):
        """
        Clear the contents of the function file.
        """
        self.file.seek(0)
        self.file.truncate()

    def close(self):
        """
        Close the function file.
        """
        self.file.close()
