execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:2b}] at @s align xyz run summon armor_stand ~0.5 ~ ~0.5 {NoGravity:1b,Invisible:true,Tags:['reddition.blocks.block_place.block_breaker'],Rotation:[180.0f,0f]}
execute as @e[type=minecraft:armor_stand,tag=reddition.blocks.block_place.block_breaker] at @s run setblock ~ ~ ~ minecraft:dropper[facing=north] keep
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:2b}] run kill @s
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:3b}] at @s align xyz run summon armor_stand ~0.5 ~ ~0.5 {NoGravity:1b,Invisible:true,Tags:['reddition.blocks.block_place.block_breaker'],Rotation:[0.0f,0f]}
execute as @e[type=minecraft:armor_stand,tag=reddition.blocks.block_place.block_breaker] at @s run setblock ~ ~ ~ minecraft:dropper[facing=south] keep
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:3b}] run kill @s
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:4b}] at @s align xyz run summon armor_stand ~0.5 ~ ~0.5 {NoGravity:1b,Invisible:true,Tags:['reddition.blocks.block_place.block_breaker'],Rotation:[90.0f,0f]}
execute as @e[type=minecraft:armor_stand,tag=reddition.blocks.block_place.block_breaker] at @s run setblock ~ ~ ~ minecraft:dropper[facing=west] keep
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:4b}] run kill @s
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:5b}] at @s align xyz run summon armor_stand ~0.5 ~ ~0.5 {NoGravity:1b,Invisible:true,Tags:['reddition.blocks.block_place.block_breaker'],Rotation:[-90.0f,0f]}
execute as @e[type=minecraft:armor_stand,tag=reddition.blocks.block_place.block_breaker] at @s run setblock ~ ~ ~ minecraft:dropper[facing=east] keep
execute as @e[type=minecraft:item_frame,nbt={Tags:['reddition.blocks.block_place.block_breaker']}] if entity @s[nbt={Facing:5b}] run kill @s